### ISSUE TITLE
ui: fix assets errors related to security headers

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware-attic/invenio-app-demomarc21#21]
![screen shot 2017-07-28 at 13 08 49](https://user-images.githubusercontent.com/1698163/28714929-0308229e-7396-11e7-9c56-59f39006986c.png)

**Comment by drjova** [comment]
the issue has been fixed with inveniosoftware/invenio-search-ui#50 , inveniosoftware/invenio-theme#108 and  inveniosoftware/invenio-theme#109
