### ISSUE TITLE
global: review sprint week 1 changes

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware-attic/invenio-app-demomarc21#26]
Review all merged PRs from first week of [sprint](https://github.com/orgs/inveniosoftware/projects/4) in demo site.

1) Make full install following the [installation guide](https://invenio-app-ils.readthedocs.io/en/latest/installation.html) and [running guide](https://invenio-app-ils.readthedocs.io/en/latest/usage.html). You may need to make development installations of the corresponding modules.
2) Check every issue in DONE column. a) Have it been properly fixed (as in does it work for an enduser in the just installed demo site)?
3) Check if all modules have been released - if not make PRs for releases.

**Comment by drjova** [comment]
🐒 checking the ``app-ils`` installation:

1. Run the installation guide
2. ``invenio users create test@test.ch -a --password=123456``
3. ``invenio run`` check the page
4. Make a search
5. Click facets option and see if the results are correct
6. Check if range facet exists
6. Do a query with special characters to see the response (**shouldn't** see 500 error)
7. Do a query with regular expressions (**shouldn't** see any 500 error )
8. Login
9. Check if the "Linked Accounts" link from the menu (**shouldn't** be there)
10. Go to ``/admin``
11. Check "User Management" has the changes
12. Check "OAI-PMH" has the changes
13. Logout
14. Try to login from the ``/search`` you should redirect back to it
14. Click Sign up for a new user, (**shouldn't** see any error)
16. Go to ``/login`` and "hack" the form with ```<input type="checkbox" name="remember" checked/>``` and click "Login" check your Cookies shouldn't have ``remember`` Cookie
17. Close your browser and open again ``app-ils`` you should be **still logged in**
15. Open Console and check for any CSP errors (**shouldn't have**)
16. Check you terminal for warning, should only the following, which is norma;:
```
--------------------------------------------------------------------------------
/Users/user/.virtualenvs/invenio-first-week/src/invenio-oaiserver/invenio_oaiserver/ext.py:150: UserWarning: Please specify the OAISERVER_ID_PREFIX configuration.default value is: oai:drjova-macbook:recid/
  app.config.get('OAISERVER_ID_PREFIX')))

--------------------------------------------------------------------------------
WARNING in ext [/Users/user/.virtualenvs/invenio-first-week/src/invenio-jsonschemas/invenio_jsonschemas/ext.py:239]:
JSONSCHEMAS_HOST is set to localhost
--------------------------------------------------------------------------------
```

TBC
