### ISSUE TITLE
accounts CSP issues

### ISSUE THREAD

**Issue by drjova** [inveniosoftware-attic/invenio-app-demomarc21#29]
In accounts there are CSP issues, probably are related with https://github.com/inveniosoftware/invenio-admin/pull/57

**Comment by lnielsen** [comment]
Screenshot?

**Comment by drjova** [comment]
<img width="1669" alt="screen shot 2017-08-09 at 10 04 00" src="https://user-images.githubusercontent.com/4287772/29111323-23224c78-7cea-11e7-9717-905d1a3bc8a0.png">

**Comment by hachreak** [comment]
@drjova do you think we can close this issue now?

**Comment by drjova** [comment]
@hachreak IMHO we have to double check first if it is related with the ``flask-admin`` CSP issue
