### ISSUE TITLE
tests: integration tests for App-ILS

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware-attic/invenio-app-demomarc21#31]
- [x] Simple test plan
- [x] As minimum one selenium test
- [ ] Script to setup local virtualenv with all modules and run tests for each module.

**Comment by ntarocco** [comment]
Missing the part: Script to setup local virtualenv with all modules and run tests for each module.

**Comment by lnielsen** [comment]
I'll extract the script part to a separate ticket!
