### ISSUE TITLE
search: "Error: Validation error." when filtering with the "years" facet

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware-attic/invenio-app-demomarc21#37]
**Problem:**
The years are displayed at the same time in a "range" widget ("years") and in a checkbox widget. Those two widget send a different query to the backend, either a range query or a multi-choice query. If the backend marked the "years" facet as a range, as it is the case [in invenio-app-ils](https://github.com/inveniosoftware/invenio-app-ils/blob/eb1c70c8c7395c9edf4853b656e8757337361d58/invenio_app_ils/config.py#L163), the search will fail with an error [message "Error: Invalid range format"](https://github.com/inveniosoftware/invenio-records-rest/blob/574a221faca3ca6bb344b1fe8a0e14c67e85f541/invenio_records_rest/facets.py#L59).

**Temporary solution:**
Create a custom temlate which will not show the checkbox widget.

**Comment by drjova** [comment]
Fixed by https://github.com/inveniosoftware/invenio-app-ils/pull/38
